# Configure the database used when in the development environment
development:
  adapter: mysql #postgresql
  # encoding: unicode
  database: meetups_development
  pool: 20
  username:
  password:

# Configure the database used when in the test environment
test:
  adapter: mysql #postgresql
  # encoding: unicode
  database: meetups_test
  pool: 20
  username:
  password:
