---
title: "More Data Structures Practice"
type: "article"
description: "Get extra practice manipulating Arrays and Hashes in Ruby"
tags: "data-structures, arrays, hashes"
ignore:
- "more-data-structures-practice.md"
