---
title: "Class Methods vs. Instance Methods"
type: "article"
description: "Describes how to define methods that do not depend on an instance of a class."
tags: "oop, class-methods, instance-methods, methods"
